"""initial

Revision ID: f16e8270346d
Revises: 
Create Date: 2026-06-13 20:27:13.268618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16e8270346d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('adapter', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=True)
    op.create_table('models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('input_cost', sa.Float(), nullable=False),
    sa.Column('output_cost', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('fallback_order', sa.Integer(), nullable=False),
    sa.Column('supports_stream', sa.Boolean(), nullable=False),
    sa.Column('supports_tools', sa.Boolean(), nullable=False),
    sa.Column('supports_vision', sa.Boolean(), nullable=False),
    sa.Column('supports_reasoning', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_model_name'), 'models', ['model_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_models_model_name'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
